### ISSUE TITLE
MAC_SDK_559c.zip is no longer available

### ISSUE THREAD

**Issue by githublemming** [sbooth/SFBAudioEngine#183]
The install script is currently failing because the file MAC_SDK_559c.zip  is no longer available on the monkeys audio website. 

There is a new version 570.

**Comment by githublemming** [comment]
When looking at the SimplePlayer-macOS I'm getting a compile error in SFBMonkeysAudioDecoder.mm  on line 180

`auto decompressor = std::unique_ptr<APE::IAPEDecompress>(CreateIAPEDecompressEx(ioInterface.get(), nullptr));`

No matching function for call to CreateAPEDecompressEx - Candidate function not viable: requires 3 arguments, but 2 were provided

**Comment by sbooth** [comment]
The install script issue is a problem with AudioXCFrameworks which is fixed in https://github.com/sbooth/AudioXCFrameworks/commit/12d7ade04dad7e01e3b6c4b07545be1adda684c3.

For the build issue, I think the `bReadOnly` parameter was added to `CreateIAPEDecompressEx` in MAC SDK 5.69 although interestingly it isn't used in the implementation. I had an older version of the xcframework in my build directory and didn't catch the API change.
