### ISSUE TITLE
The audio frameworks for arm64

### ISSUE THREAD

**Issue by vhikd** [sbooth/SFBAudioEngine#50]
Hello ,
Could you teach me how to build the audio frameworks in this project ? Just one example.
Thank you very much.

**Comment by sbooth** [comment]
Since the dependencies for iOS all use `autoconf` I use a wrapper to invoke `configure` with the appropriate arguments.  I install the headers and static libraries initially to `/tmp` and then copy them manually to the appropriate architecture folder in `Libraries`.  For arm64 I would name the folder `ios-arm64-clang-libc++`. The project file adjusts its search paths based on the build architecture, so you'd have to add a separate arm64 entry pointing to this folder for the headers and libraries.  It is also possible to combine the libraries into a single "fat" one using `lipo` but I had problems doing this in the past (I can't remember specifically what now) which is why I went with the current setup.

I attempted to create a `configure` wrapper for iOS 8.1 and arm64 at https://github.com/sbooth/iOS-autoconf/blob/master/iphone-8.1-arm64-configure . I was able to compile `mpg123` as a test but I have not yet attempted to build everything.

**Comment by vhikd** [comment]
Thanks for your reply, I will try with it.

**Comment by horaceho** [comment]
Any chance to release `SFBAudioEngine-dependencies` source code so there will be no worry of architectural dependency of the library?

**Comment by jazperader** [comment]
Crap... No I can't something went terribly wrong with my repos. Sorry for that man. Should've mentioned that earlier.

Regards, J

**Comment by sbooth** [comment]
@horaceho The dependencies are all open source libraries so the source code is already available.

**Comment by horaceho** [comment]
@sbooth thanks!

**Comment by vhikd** [comment]
@sbooth 
I had build all of the library used in the project but the libtta . I have tried v2.2 and v2.3
When I run ./arm64-configure in the terminal, it turned out errors as follows.

checking build system type... i686-apple-darwin14.1.0
checking host system type... Invalid configuration `aarch64-apple-darwin': machine `aarch64-apple' not recognized
configure: error: /bin/sh ./config.sub aarch64-apple-darwin failed

Did it mean that this library was not support for arm64?

**Comment by sbooth** [comment]
I think it's more likely that tta just ships with older versions of the autoconf tools.  Hopefully you should be able to run `autoreconf --force` to pull in newer versions and build from there.

**Comment by vhikd** [comment]
@sbooth 
Oh my god. I have try my best. I couldn't work it out . I download tta(tta++) source code from http://sourceforge.net/projects/tta/files/tta/  . The configure file in it will build the lib with x86_64 . I tried to change any configure and failed at last . Any suggestion?

**Comment by woc2006** [comment]
How can I build all dependices with arm64, I tried your configure wrapper but it said ./configure: No such file or directory

**Comment by woc2006** [comment]
I use your wrapper to build all dependencies with arm64, use lipo to create a single fat lib, change library search path to my fat path. But XCode still reported "Undefined symbols for architecture arm64" when I tried to archive SimplePlayer-iOS project.

```
lipo -info /arm64/libmpg123.a
Architectures in the fat file: libmpg123.a are:  arm64 

lipo -info libSFBAudioEngine.a
Architectures in the fat file: libSFBAudioEngine.a are: armv7 arm64 
```

**Comment by tvquan** [comment]
Still not compile successful on iOS, both simulator and device, with Xcode 7

**Comment by sbooth** [comment]
These are posted at https://files.sbooth.org/SFBAudioEngine-dependencies.tar.bz2
